	[mixin.perf]
		#Replace buildSurface with optimized implementation
		# defaultValue: true
		# incompatibleWith: biolith
		#
		surface = true
		#Replace populateNoise with optimized implementation
		# defaultValue: true
		#
		noise = true
		#Replace populateBiomes with optimized implementation
		# defaultValue: true
		#
		biome = true

	[mixin.debug]
		#Disable carve, features and entites chunk generation step
		# defaultValue: false
		#
		disable_carve_features_and_entities = false

	[perf.surface]
		#Predict biomes in advance in surface builder. Major speedup for surface builder
		# (depends on surface builder mixin)
		# defaultValue: true
		#
		biome = true
		#Max size of surface rule compiler cache per gb of allocated memory
		# defaultValue: 100
		# min: 16 max: 65536
		#
		max_cache_size_per_gb = 100
		#Skip trivial surface builder. Major speedup for end dimension. Depends on surface builder
		# (depends on surface builder mixin)
		# defaultValue: true
		#
		trivial = true

	[perf.biomes]
		#Optimize biome tree by avoiding multiple calls to thread local
		# defaultValue: false
		# incompatibleWith: biolith
		#
		tree = false
		#Optimize end biome generation (2x speed) but may cause mod incompatibility
		# defaultValue: true
		# incompatibleWith: biolith
		#
		end = true
		#Optimize single biome generation (major speedup) but may cause mod incompatibility
		# defaultValue: true
		#
		fixed = true
