name = "Kucing testpack"
author = "apuru-katze"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dfc6da18542e2d590b50d46e84de1862c7d0c9fe474cdb95142c9a932a3ac5b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
