name = "Kucing testpack"
author = "apuru-katze"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e52df3d993fe639aca6d7818a917a4014bc116dc82fbe3ae71736bd7bc2a5e53"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
unsup = "1.1.6"
