name = "Kucing testpack"
author = "apuru-katze"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3ea82b40c5591b33d5bbaf4761dfba026b972c069cca8e3ac478ff0ebd2e6d8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
unsup = "1.1.6"
